name: ar-indivbustax25-dev3
channels:
- conda-forge
dependencies:
- python>=3.10, <3.13
- ipython
- ipykernel
- jupyter
- numpy
- pandas>=1.4.4
- bokeh>=3.4.0
- matplotlib
- plotly
- pip
- pip:
  - policyengine-core==3.16.3
  - policyengine-us==1.221.0
  - cost-of-capital-calculator
  - behresp
  - bokeh_sampledata
  - selenium
  - geopandas
  - openpyxl
